from os import getenv

DB_NAME = getenv("DB_NAME")
DB_USERNAME = getenv("DB_USERNAME")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_HOST = getenv("DB_HOST")

CLOUD_NAME = getenv("CLOUD_NAME")
API_KEY = getenv("API_KEY")
API_SECRET = getenv("API_SECRET")

MAILTRAP_SERVER = getenv("MAIL_SERVER")
MAILTRAP_PORT = getenv("MAIL_PORT")
MAILTRAP_USERNAME = getenv("MAIL_USERNAME")
MAILTRAP_PASSWORD = getenv("MAIL_PASSWORD")
MAILTRAP_USE_TLS: bool = getenv("MAIL_USE_TLS")
MAILTRAP_USE_SSL: bool = getenv("MAIL_USE_SSL")

SECRET_KEY = getenv("SECRET_KEY")